### ISSUE TITLE
Coil extension Content Security Policy violation prevents loading

### ISSUE THREAD

**Issue by wmurphyrd** [coilhq/web-monetization-projects#1248]
Hi It's Will from Immers Space, one of the Grant for the Web flagships. 

When I try to use Firefox Coil add-on with a production site using Content Security Policy, the `document.monetization` polyfill fails to load and the Coil add-on generates a CSP console error:

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content.js:21:461461
```

This error can be observed here: https://hub.medieval-castle.club/

Here's some [documentation from Mozilla on the issue wrt addons](https://blog.mozilla.org/addons/2019/12/12/test-the-new-csp-for-content-scripts/). I can open up CSP to inline sources to get it working now, but I'd rather not leave that vulnerability open long-term.

**Comment by sublimator** [comment]
Thanks for the report, will look into it in the coming days

**Comment by wmurphyrd** [comment]
I was able to get it working at the above url by adding the following 4 script hashes to my `script-src` directive:

```
'sha256-W5yaJ6UM3/kOJa12aRVSLOEOKdAUYAWZPM1bUuaTJYQ=' 
'sha256-XpyxuqRQmj1o8ovYZlIA71UXSYTvYdV8kOb55p+lrNo='
'sha256-tie542PGbiDGOm9MefVIzDBZf4Nt5wTagAHT/BKEB94='
'sha256-9QLzkf1LE5s0CtnpqUvwkWr7DV4GRfQLGt/tFNT19h0='
```

This covers the initial polyfill script, and the 3 versions of the `monetization.state` update script. I think adding these to the add-on manifest under content_security_policy.content_scripts may solve the issue everywhere

Since the initial link is now fixed, here's a new one to obvserve the error https://nebulous-confused-twig.glitch.me/ ([source](https://glitch.com/edit/#!/nebulous-confused-twig?path=server.js%3A41%3A33))

**Comment by sublimator** [comment]
Thanks for the update

**Comment by sublimator** [comment]
I've had a quick look at this link and it seems that this is referring to manifest v3, rather than v2?  
https://blog.mozilla.org/addons/2019/12/12/test-the-new-csp-for-content-scripts/

I experimented with the new "content_security_policy" as an object, didn't really see any effect, then tried converting to manifest version 3, but was unable to load the add-on:
![image](https://user-images.githubusercontent.com/525211/97829333-5480de00-1cfc-11eb-9db4-9d8f7ba7e54a.png)

Will keep looking into this as time permits. 

Glad that you seem to be able to list the individual script hashes in your CSP!

**Comment by sublimator** [comment]
For the record, I also tried adding the hashes to the old v2 manifest "content_security_policy" single string value, but it didn't seem to work. 

I'm not sure about this, but by my understanding, the CSP declared in the page headers has the final say here, and if one wants a tight CSP, then an allow list exempting the various script injections is the only option?

**Comment by justmoon** [comment]
Quick disclaimer: I only took a cursory glance at this and haven't touched the extension in a long time so apologies if I say something dumb.

My read on this is that currently, the extension actually adds a script to the page itself which then runs as part of the JavaScript in the page context. Since the page's CSP applies to all code run inside of the page, it will (correctly) block this injection.

My evidence for is that the error message @wmurphyd posted says the error occurred at "content.js:21:461461", meaning that content script actually ran and got to the point where it tried to inject some other JS code into the page.

In my opinion, the fix is probably a refactor of the extension to move all of the injected code into the content script. This should be possible in principle, because the content script has access to the page's DOM, so it _should_ be able to setup any event listeners etc. it needs without loading extra scripts. (Not 100% sure.)

Refactoring our code may not be all that's required. Sometimes you also have third party libraries calling eval as part of polyfills or overengineered code, so you have to often chase down those cases and remove those third party libraries or file upstream bugs. You also have to make sure your build process is CSP friendly. Most build tools have documentation on how to use them with CSP, e.g.: https://webpack.js.org/guides/csp/


> I experimented with the new "content_security_policy" as an object, didn't really see any effect, then tried converting to manifest version 3, but was unable to load the add-on:

I couldn't find any more recent mentions from Mozilla regarding Manifest v3, so I assume it just never ended up rolling out (yet). That said, I don't think we need this feature if we can do the refactor I suggested.

Refactoring the extension in this way is a good idea anyway. The injected code should be only the absolute minimum required to allow the extension to do its job, so it should pretty much be just an interface which sends messages about added and removed meta tags and receives corresponding monetization events to emit in the page. There _should_ be no reason that that can't be a simple, single-file script with no external dependencies which is then minified and run as a content script without injecting anything into the page. This would also make it more easily auditable from a security perspective to have the most trusted code be minimal.

**Comment by sublimator** [comment]
@justmoon 

Thanks for the help

> I couldn't find any more recent mentions from Mozilla regarding Manifest v3

Yeah, Google' documentation seems a bit stale too. Hard to tell if it's abandoned or simply running late.

> Refactoring the extension 
> only the absolute minimum required to allow the extension to do its job

Yeah, if were communicating via an existing DOM object, we should be able to emit events across contexts. I will keep looking, but can't presently see how we can create a `document.monetization` object without `<script>${code}</script>` injection to set it in the correct context. We would have the same problem with a `window.monetization` that [has been proposed](https://github.com/WICG/webmonetization/issues/24). 

`monetizationXXX` events emitted directly on the window would work, but that's a breaking change.

**Comment by sublimator** [comment]
https://github.com/coilhq/web-monetization-projects/pull/1254

**Comment by sublimator** [comment]
@sharafian pointed out that maybe we could intercept the requests using extension apis and modify the CSP headers. 
It would require extra permissions, but it would also allow us to impl Link header. Expressed a preference for Document over Window if had to choose an existing DOM object to dispatch events to.

**Comment by sublimator** [comment]
For the record:

Not having much joy in modifying response headers with FF (chrome yes).
To sanity test it wasn't my own buggy code, I tried a few FF addons:
https://addons.mozilla.org/en-US/firefox/addon/modheader-firefox/
https://addons.mozilla.org/en-US/firefox/addon/simple-modify-header/

Even with those, no bueno :confused:

Note also you need to use two extra permissions:
"webRequest", "webRequestBlocking"

**Comment by sublimator** [comment]
@wmurphyrd suggested that integrators with CSP concerns could simply include a single polyfill snippet (see #1254) on their main page. That seems a reasonable solution to me.

**Comment by sharafian** [comment]
> wmurphyrd suggested that integrators with CSP concerns could simply include a single polyfill snippet (see #1254) on their main page. That seems a reasonable solution to me.

I like that idea, it seems the simplest fix

**Comment by sublimator** [comment]
https://github.com/coilhq/web-monetization-projects/blob/8645ca51611be79bbfc422920d6e944bcb3b135a/packages/web-monetization-wext/src/content/DocumentMonetization.ts#L35-L41

So I updated the extension to try/catch per @wmurphyrd suggestion and also to console.warn the polyfill code: 

https://github.com/coilhq/web-monetization-projects/blob/8645ca51611be79bbfc422920d6e944bcb3b135a/packages/web-monetization-wext/src/content/wmPolyfill.ts#L50-L54
