### ISSUE TITLE
No WM events in Firefox when extension is installed but user is signed out

### ISSUE THREAD

**Issue by melissahenderson** [coilhq/web-monetization-projects#1941]
While testing the Coil Blogs migration with Write.as, we found that when you're logged out of the Firefox extension, no WM events are fired.

Scenario:
Viewed web monetized content on Write.as without the Coil extension installed in Firefox. Was presented with a "full" message: "Continue reading with a Coil membership", some additional info, and two buttons (Get Started and Learn More). Viewed WM'd content on Write.as with the Coil extension installed in Firefox, but not signed in to my Coil account. Only received the string, "Continue reading with a Coil membership."

The full message doesn't appear because no WM events fire at all. This isn't the case with the Chrome extension. The full message appears when the extension is installed but the user is signed out.

**Comment by sublimator** [comment]
@melissahenderson 
> web monetized content on Write.as

Thanks, could you share a link ?

**Comment by melissahenderson** [comment]
Test posts: https://write.as/melcoil/
Firefox 88.0.1 on Mac OS 10.15.7

The statement about the events not firing came through Matt @ Write.as after checking his logs, but he was able to duplicate the issue. If you need his specs, let me know.

**Comment by sublimator** [comment]
Note this is the same behavior on Chrome, and I believe to be expected ? 
What event[s] were you expecting ? 
For example, if a pending event was emitted, it would only have to be quickly followed by a stop due to there being no token to support monetization. 

To reiterate, neither Chrome and Firefox emit any WM events if the extension is installed and no user is logged in. (aside: document.monetization *is* injected) 

I note that on Chrome when logged out we see the CTA box:
![image](https://user-images.githubusercontent.com/525211/119757142-b8ecd000-bece-11eb-8d06-d37d50b43dc8.png)

Whereas on FF it looks like so: 
![image](https://user-images.githubusercontent.com/525211/119757158-bee2b100-bece-11eb-9700-57c6a619dcea.png)

**Comment by sublimator** [comment]
I set localStorage.WM_DEBUG which should log any monetization events apart from progress and I'm not seeing them when logged out on Chrome, however this code is mysteriously executing: 
![image](https://user-images.githubusercontent.com/525211/119758691-200b8400-bed1-11eb-843a-449913d5faf4.png)

**Comment by sublimator** [comment]
So the logging was missing simply because I didn't see that a filter was in place (duh) 
![image](https://user-images.githubusercontent.com/525211/119759508-9492f280-bed2-11eb-86eb-f2921f93f044.png)

**Comment by sublimator** [comment]
I believe the problem is that on Firefox the load event is not being fired here:
https://github.com/coilhq/web-monetization-projects/blob/a8603cce431d9198d1d340f6ee07aff91cc13791/packages/coil-extension/src/background/services/SiteToken.ts#L23-L28

In the background page this code stalls:
![image](https://user-images.githubusercontent.com/525211/119760894-0e2be000-bed5-11eb-8989-edbe8a07fae8.png)

If you run that code in some other content (such as the test page mentioned) the code will complete.

**Comment by sublimator** [comment]
So we know why FF isn't emitting the event. There's some issue with the extension, but the bigger question is should we actually be emitting the stop event at all? 
I think it's more a bug that it is.
