### ISSUE TITLE
401 failed to get token signature until log out then back in

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#526]
![image](https://user-images.githubusercontent.com/525211/78973916-07100a00-7b3b-11ea-941a-cb4efd2907bc.png)
```
 coil-extension:background:AnonymousTokens  token /issue failed status=%d 401
Stream.ts:105  coil-extension:background:Stream  error streaming. retry in 2s. err= failed to get token signature. code=401 Error: failed to get token signature. code=401
```
Steps to repro:
- Sign out 
- Create new user with $baseEmail+$timestampMs@coil.com
- Expected: Monetization should work
  - Actual: Monetization does NOT work
  - Check background page to see error
- Sign out 
- Sign back in with new user
- Expected: Monetization works

**Comment by sharafian** [comment]
Maybe this is a bug in the whoami fixes by @sentientwaffle ? If the extension weren't able to acquire a token then it could trigger a 401 when it tries to get tokens

**Comment by sentientwaffle** [comment]
It might be related. But it the extension does have an auth token, it just doesn't include `agg`,`throughput`,etc, since the token was generated without a subscription. But then if you add a card to the account, the token doesn't refresh (since it hasn't expired). I'm actually not sure why this but doesn't exist right now, with the current version of the extension & backend.

**Comment by sharafian** [comment]
The extension pretty much refreshes its token every page load in the previous version, so maybe that was stopping this from happening

**Comment by sentientwaffle** [comment]
Fixed by https://github.com/coilhq/coil/pull/3424 (which isn't in prod yet, fyi).
